// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-BOyx-N5UE8fLupHn5G7y_OmFJu7Jwd0',
    appId: '1:975942106452:web:7e988a661ab0b8a5431cc1',
    messagingSenderId: '975942106452',
    projectId: 'galerieimages-b35c7',
    authDomain: 'galerieimages-b35c7.firebaseapp.com',
    storageBucket: 'galerieimages-b35c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHNHpokmY-JgVhfknqMQK-zUpEwxEPCmI',
    appId: '1:975942106452:android:c0467aea84f9deb8431cc1',
    messagingSenderId: '975942106452',
    projectId: 'galerieimages-b35c7',
    storageBucket: 'galerieimages-b35c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLVJ0K4He69G_Z3SPk10qcynCs3_jmeg',
    appId: '1:975942106452:ios:ef505f13156c2acd431cc1',
    messagingSenderId: '975942106452',
    projectId: 'galerieimages-b35c7',
    storageBucket: 'galerieimages-b35c7.appspot.com',
    iosClientId: '975942106452-6m2rjaugdu1rh1b9dnjhn8lvjae0bvpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.galerieImagesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLVJ0K4He69G_Z3SPk10qcynCs3_jmeg',
    appId: '1:975942106452:ios:ef505f13156c2acd431cc1',
    messagingSenderId: '975942106452',
    projectId: 'galerieimages-b35c7',
    storageBucket: 'galerieimages-b35c7.appspot.com',
    iosClientId: '975942106452-6m2rjaugdu1rh1b9dnjhn8lvjae0bvpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.galerieImagesApp',
  );
}
